repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml

  #- repo: https://github.com/astral-sh/ruff-pre-commit
  #  rev: 'v0.9.9'
  #  hooks:
      # - id: ruff
      #   args: [ --fix, --exit-non-zero-on-fix ]
      # Run the formatter
      # - id: ruff-format

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.47.0
    hooks:
      - id: markdownlint
        args: ["--disable", "MD013"]

  #- repo: https://github.com/crate-ci/typos
  #  rev: v1.30.0
  #  hooks:
  #    - id: typos

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.21.2
    hooks:
      - id: pyupgrade

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.36.1
    hooks:
      - id: check-renovate
        args: ["--verbose"]

  - repo: https://github.com/PyCQA/bandit
    rev: 1.9.3
    hooks:
    - id: bandit
